#! /bin/bash

if [[ $2 == "" ]]; then
	module="cache"
else
	module="$2"
fi

if [ -f ./output/$module\_tb.lxt ]; then
	rm ./output/$module\_tb.lxt
fi
iverilog -Wall -o output/$module\_tb.vvp tb/$module\_tb.v src/$module\.v && vvp output/$module\_tb.vvp -lxt2
if ! [[ $1 == "-q" ]]; then
	gtkwave output/$module\_tb.lxt output/$module\_tb.gtkw >> /dev/null & disown && sleep 2 && echo ''
fi

